DELETE FROM `spell_script_names` WHERE `ScriptName` IN (
    'spell_dk_t15_blood_4p_bonus',
    'spell_dru_glyph_of_the_predator',
    'spell_gen_deserter',
    'spell_hunt_glyph_of_deterrence',
    'spell_mage_greater_invisibility_damage_reduction',
    'spell_monk_charging_ox_wave',
    'spell_monk_charging_ox_wave_visual',
    'spell_pal_sword_of_light_damage_bonus_holy',
    'spell_pal_glyph_of_bladed_judgement',
    'spell_sha_stone_bulwark_totem_passive',
    'spell_warl_haunt',
    'spell_warl_ember_test',
    'spell_warl_glyph_of_felguard',
    'spell_warl_glyph_of_felguard_loading',
    'spell_warl_glyph_of_verdant_spheres'
);

INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(49222, 'spell_dk_t15_blood_4p_bonus'),
(5225, 'spell_dru_glyph_of_the_predator'),
(114280, 'spell_dru_glyph_of_the_predator'),
(26013, 'spell_gen_deserter'),
(19263, 'spell_hunt_glyph_of_deterrence'),
(148467, 'spell_hunt_glyph_of_deterrence'),
(113862, 'spell_mage_greater_invisibility_damage_reduction'),
(119392, 'spell_monk_charging_ox_wave'),
(125084, 'spell_monk_charging_ox_wave_visual'),
(24275, 'spell_pal_sword_of_light_damage_bonus_holy'),
(20271, 'spell_pal_sword_of_light_damage_bonus_holy'),
(112266, 'spell_pal_glyph_of_bladed_judgement'),
(114889, 'spell_sha_stone_bulwark_totem_passive'),
(48181, 'spell_warl_haunt'),
(116860, 'spell_warl_ember_test'),
(30146, 'spell_warl_glyph_of_felguard'),
(112870, 'spell_warl_glyph_of_felguard'),
(111898, 'spell_warl_glyph_of_felguard'),
(6962, 'spell_warl_glyph_of_felguard_loading'),
(56241, 'spell_warl_glyph_of_verdant_spheres');
